In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-1, -2], [-3, -4], [-5, -6]])

# (2X3) dot product (3X2) == (2X2) 행렬
C = np.dot(A, B) # 행렬 곱 수행

# matrix A, B 형상 출력 => shape
print("A.shape ==", A.shape, "B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


In [4]:
D = np.dot(B, A)
print(D)

[[ -9 -12 -15]
 [-19 -26 -33]
 [-29 -40 -51]]


In [6]:
# broadcast
# numpy에서는 크기가 다른 두 행렬간에도 사칙연산 (+, -, *, /)을 할 수 있는데
# 이를 브로드 캐스트(boradcast)라고 지칭함
# => 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산

A = np.array([[1, 2], [3, 4]])
b = 5

print(A + b)

[[6 7]
 [8 9]]


In [7]:
C = np.array([[1, 2], [3, 4]])
D = np.array([4, 5])

print(C + D)

[[5 7]
 [7 9]]


In [8]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = A.T # A의 전치행렬

print("A.shape ==", A.shape, "B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2) B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [9]:
# vector 전치행렬
C = np.array([1, 2, 3, 4, 5]) #vector, matrix 아님
D = C.T # C는 vector 이므로 transpose 안됨

E = C.reshape(1, 5)
F = E.T 

print("C.shape ==", C.shape, "D.shape ==", D.shape)
print("E.shape ==", E.shape, "F.shape ==", F.shape)
print(F)

C.shape == (5,) D.shape == (5,)
E.shape == (1, 5) F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
# numpy 행렬 indexing/slicing
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [11]:
print("A[0][0] ==", A[0, 0], "A[0][1] ==", A[0, 1])
print("A[1][0] ==", A[1, 0], "A[1][1] ==", A[1, 1])

A[0][0] == 10 A[0][1] == 20
A[1][0] == 30 A[1][1] == 40


In [12]:
print("A[0:-1, 1:2] ==", A[0:-1, 1:2])

A[0:-1, 1:2] == [[20]
 [40]]


In [14]:
print("A[:, 0] ==", A[:, 0], A[:, 0].shape)
print("A[:, :] ==", A[:, :])

A[:, 0] == [10 30 50] (3,)
A[:, :] == [[10 20]
 [30 40]
 [50 60]]


In [16]:
# numpy 행렬 iterator
# 행렬 모든 원서를 access 하는 경우에는 iterator 사용 가능

A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

# 행렬 A의 iterator 생성
it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    print("current val ==", A[idx])
    it.iternext()
    

current val == 10
current val == 20
current val == 30
current val == 40
current val == 50
current val == 60
current val == 70
current val == 80
